### ISSUE TITLE
结合elasticsearch6.x使用出错

### ISSUE THREAD

**Issue by likanghai** [AliyunContainerService/log-pilot#110]
无法结合elasticsearch6.x使用，但是curl http://elasticsearch:9200正常
`2018-05-05 18:42:40 +0800 [info]: following tail of /host/logs/access.log
2018-05-05 18:42:40 +0800 [info]: following tail of /host/logs/access.log
2018-05-05 18:42:50 +0800 [info]: Connection opened to Elasticsearch cluster => {:host=>"192.168.1.30", :port=>9200, :scheme=>"http"}
2018-05-05 18:42:50 +0800 [warn]: temporarily failed to flush the buffer. next_retry=2018-05-05 18:42:51 +0800 error_class="Elasticsearch::Transport::Transport::Errors::NotAcceptable" error="[406] {\"error\":\"Content-Type header [] is not supported\",\"status\":406}" plugin_id="object:2ac3535a8b24"
  2018-05-05 18:42:50 +0800 [warn]: /usr/lib/ruby/gems/2.3.0/gems/elasticsearch-transport-5.0.3/lib/elasticsearch/transport/transport/base.rb:201:in `__raise_transport_error'
  2018-05-05 18:42:50 +0800 [warn]: /usr/lib/ruby/gems/2.3.0/gems/elasticsearch-transport-5.0.3/lib/elasticsearch/transport/transport/base.rb:318:in `perform_request'
  2018-05-05 18:42:50 +0800 [warn]: /usr/lib/ruby/gems/2.3.0/gems/elasticsearch-transport-5.0.3/lib/elasticsearch/transport/transport/http/faraday.rb:20:in `perform_request'
  2018-05-05 18:42:50 +0800 [warn]: /usr/lib/ruby/gems/2.3.0/gems/elasticsearch-transport-5.0.3/lib/elasticsearch/transport/client.rb:131:in `perform_request'
  2018-05-05 18:42:50 +0800 [warn]: /usr/lib/ruby/gems/2.3.0/gems/elasticsearch-api-5.0.3/lib/elasticsearch/api/actions/bulk.rb:95:in `bulk'
  2018-05-05 18:42:50 +0800 [warn]: /usr/lib/ruby/gems/2.3.0/gems/fluent-plugin-elasticsearch-1.9.3/lib/fluent/plugin/out_elasticsearch.rb:353:in `send_bulk'
  2018-05-05 18:42:50 +0800 [warn]: /usr/lib/ruby/gems/2.3.0/gems/fluent-plugin-elasticsearch-1.9.3/lib/fluent/plugin/out_elasticsearch.rb:339:in `write_objects'
  2018-05-05 18:42:50 +0800 [warn]: /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.12.34/lib/fluent/output.rb:490:in `write'
  2018-05-05 18:42:50 +0800 [warn]: /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.12.34/lib/fluent/buffer.rb:354:in `write_chunk'
  2018-05-05 18:42:50 +0800 [warn]: /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.12.34/lib/fluent/buffer.rb:333:in `pop'
  2018-05-05 18:42:50 +0800 [warn]: /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.12.34/lib/fluent/output.rb:342:in `try_flush'
  2018-05-05 18:42:50 +0800 [warn]: /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.12.34/lib/fluent/output.rb:149:in `run'
2018-05-05 18:42:51 +0800 [info]: Connection opened to Elasticsearch cluster => {:host=>"192.168.1.30", :port=>9200, :scheme=>"http"}
2018-05-05 18:42:51 +0800 [warn]: temporarily failed to flush the buffer. next_retry=2018-05-05 18:42:53 +0800 error_class="Elasticsearch::Transport::Transport::Errors::NotAcceptable" error="[406] {\"error\":\"Content-Type header [] is not supported\",\"status\":406}" plugin_id="object:2ac3535a8b24"
  2018-05-05 18:42:51 +0800 [warn]: suppressed same stacktrace
2018-05-05 18:42:53 +0800 [info]: Connection opened to Elasticsearch cluster => {:host=>"192.168.1.30", :port=>9200, :scheme=>"http"}
2018-05-05 18:42:53 +0800 [warn]: temporarily failed to flush the buffer. next_retry=2018-05-05 18:42:57 +0800 error_class="Elasticsearch::Transport::Transport::Errors::NotAcceptable" error="[406] {\"error\":\"Content-Type header [] is not supported\",\"status\":406}" plugin_id="object:2ac3535a8b24"
  2018-05-05 18:42:53 +0800 [warn]: suppressed same stacktrace

**Comment by songyingjun** [comment]
用最新的镜像registry.cn-hangzhou.aliyuncs.com/acs-sample/log-pilot:latest

**Comment by chenqz1987** [comment]
@songyingjun 使用registry.cn-hangzhou.aliyuncs.com/acs-sample/log-pilot:0.9.3-filebeat看下
