### ISSUE TITLE
fluentd 模式docker启动报错

### ISSUE THREAD

**Issue by haoyangyi** [AliyunContainerService/log-pilot#135]
启动命令：
docker run --rm -it \
   -v /var/run/docker.sock:/var/run/docker.sock \
   -v /:/host \
   -e PILOT_TYPE=fluentd \
   registry.cn-hangzhou.aliyuncs.com/acs-sample/log-pilot:latest
错误如下:
enable pilot: fluentd
Traceback (most recent call last):
  File "/pilot/entrypoint", line 58, in <module>
    config()
  File "/pilot/entrypoint", line 54, in config
    subprocess.check_call(['/pilot/config.fluentd'])
  File "/usr/lib/python2.7/subprocess.py", line 181, in check_call
    retcode = call(*popenargs, **kwargs)
  File "/usr/lib/python2.7/subprocess.py", line 168, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/usr/lib/python2.7/subprocess.py", line 390, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1025, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

**Comment by glwlg** [comment]
我也有这个问题

**Comment by chenquanzhao** [comment]
那个镜像版本比较老了，可以如下测试：
```
docker run --privileged --rm -it -v /var/run/docker.sock:/var/run/docker.sock -v /:/host -e PILOT_TYPE=fluentd registry.cn-hangzhou.aliyuncs.com/acs-sample/log-pilot:0.9.5-fluent
```

**Comment by haoyangyi** [comment]
谢谢，测试通过是ok的
