### ISSUE TITLE
log-pilot filebeat 镜像运行出错，按源码中Dockerfile.filebeat 编译的镜像

### ISSUE THREAD

**Issue by zhouwudong** [AliyunContainerService/log-pilot#145]
enable pilot: filebeat,
Traceback (most recent call last):,
  File "/pilot/entrypoint", line 58, in <module>,
    config(),
  File "/pilot/entrypoint", line 51, in config,
    subprocess.check_call(['/pilot/config.filebeat']),
  File "/usr/lib/python2.7/subprocess.py", line 185, in check_call,
    retcode = call(*popenargs, **kwargs),
  File "/usr/lib/python2.7/subprocess.py", line 172, in call,
    return Popen(*popenargs, **kwargs).wait(),
  File "/usr/lib/python2.7/subprocess.py", line 394, in __init__,
    errread, errwrite),
  File "/usr/lib/python2.7/subprocess.py", line 1047, in _execute_child,
    raise child_exception,
OSError: [Errno 13] Permission denied,

**Comment by chenquanzhao** [comment]
@zhouwudong 看起来是/pilot/config.filebeat 没有可执行权限，一种可以修改下本地目录下的config.filebeat加下可执行权限，一种可以在Dockerfile.filebeat里加上可执行权限，后续我们也更新下dockerfile，谢谢！

**Comment by chenquanzhao** [comment]
@zhouwudong 可以基于最新主干代码构建，已加入权限修改的指令
