### ISSUE TITLE
failed to flush the buffer. retry_time=0 next_retry_seconds=2017-11-12 12:55:43 +0000 chunk="55dc8aba9dbc2342f98607c506e7f654" error_class=Encoding::UndefinedConversionError error="\"\\xE5\" from ASCII-8BIT to UTF-8"

### ISSUE THREAD

**Issue by haqiaolong** [AliyunContainerService/log-pilot#66]
hi 我用 graylog去收集日志 全英文的没问题 但是包含中文 就报错，报错如下：
2017-11-12 12:55:42 +0000 [warn]: #0 /usr/lib/ruby/gems/2.3.0/gems/gelf-3.0.0/lib/gelf/notifier.rb:160:in `encode'
  2017-11-12 12:55:42 +0000 [warn]: #0 /usr/lib/ruby/gems/2.3.0/gems/gelf-3.0.0/lib/gelf/notifier.rb:160:in `to_json'
  2017-11-12 12:55:42 +0000 [warn]: #0 /usr/lib/ruby/gems/2.3.0/gems/gelf-3.0.0/lib/gelf/notifier.rb:160:in `notify_with_level!'
  2017-11-12 12:55:42 +0000 [warn]: #0 /usr/lib/ruby/gems/2.3.0/gems/gelf-3.0.0/lib/gelf/notifier.rb:119:in `notify!'
  2017-11-12 12:55:42 +0000 [warn]: #0 /etc/fluentd/plugins/out_gelf.rb:119:in `block in write'
  2017-11-12 12:55:42 +0000 [warn]: #0 /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.14.22/lib/fluent/event.rb:323:in `each'
  2017-11-12 12:55:42 +0000 [warn]: #0 /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.14.22/lib/fluent/event.rb:323:in `block in each'
  2017-11-12 12:55:42 +0000 [warn]: #0 /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.14.22/lib/fluent/plugin/buffer/memory_chunk.rb:80:in `open'
  2017-11-12 12:55:42 +0000 [warn]: #0 /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.14.22/lib/fluent/plugin/buffer/memory_chunk.rb:80:in `open'
  2017-11-12 12:55:42 +0000 [warn]: #0 /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.14.22/lib/fluent/event.rb:322:in `each'
  2017-11-12 12:55:42 +0000 [warn]: #0 /etc/fluentd/plugins/out_gelf.rb:118:in `write'
  2017-11-12 12:55:42 +0000 [warn]: #0 /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.14.22/lib/fluent/compat/output.rb:131:in `write'
  2017-11-12 12:55:42 +0000 [warn]: #0 /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.14.22/lib/fluent/plugin/output.rb:1089:in `try_flush'
  2017-11-12 12:55:42 +0000 [warn]: #0 /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.14.22/lib/fluent/plugin/output.rb:1314:in `flush_thread_run'
  2017-11-12 12:55:42 +0000 [warn]: #0 /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.14.22/lib/fluent/plugin/output.rb:439:in `block (2 levels) in start'
  2017-11-12 12:55:42 +0000 [warn]: #0 /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.14.22/lib/fluent/plugin_helper/thread.rb:78:in `block in thread_create'
2017-11-12 12:55:43 +0000 [warn]: #0 failed to flush the buffer. retry_time=0 next_retry_seconds=2017-11-12 12:55:43 +0000 chunk="55dc8aba9dbc2342f98607c506e7f654" error_class=Encoding::UndefinedConversionError error="\"\\xE5\" from ASCII-8BIT to UTF-8"
  2017-11-12 12:55:43 +0000 [warn]: #0 suppressed same stacktrace
2017-11-12 12:55:44 +0000 [warn]: #0 failed to flush the buffer. retry_time=1 next_retry_seconds=2017-11-12 12:55:44 +0000 chunk="55dc8aba9dbc2342f98607c506e7f654" error_class=Encoding::UndefinedConversionError error="\"\\xE5\" from ASCII-8BIT to UTF-8"
  2017-11-12 12:55:44 +0000 [warn]: #0 suppressed same stacktrace
2017-11-12 12:55:46 +0000 [warn]: #0 failed to flush the buffer. retry_time=2 next_retry_seconds=2017-11-12 12:55:46 +0000 chunk="55dc8aba9dbc2342f98607c506e7f654" error_class=Encoding::UndefinedConversionError error="\"\\xE5\" from ASCII-8BIT to UTF-8"
  2017-11-12 12:55:46 +0000 [warn]: #0 suppressed same stacktrace
2017-11-12 12:55:50 +0000 [warn]: #0 failed to flush the buffer. retry_time=3 next_retry_seconds=2017-11-12 12:55:50 +0000 chunk="55dc8aba9dbc2342f98607c506e7f654" error_class=Encoding::UndefinedConversionError error="\"\\xE5\" from ASCII-8BIT to UTF-8"
  2017-11-12 12:55:50 +0000 [warn]: #0 suppressed same stacktrace
2017-11-12 12:55:58 +0000 [warn]: #0 failed to flush the buffer. retry_time=4 next_retry_seconds=2017-11-12 12:55:58 +0000 chunk="55dc8aba9dbc2342f98607c506e7f654" error_class=Encoding::UndefinedConversionError error="\"\\xE5\" from ASCII-8BIT to UTF-8"
  2017-11-12 12:55:58 +0000 [warn]: #0 suppressed same stacktrace
^C^C^C^C2017-11-12 12:56:15 +0000 [warn]: #0 failed to flush the buffer. retry_time=5 next_retry_seconds=2017-11-12 12:56:15 +0000 chunk="55dc8aba9dbc2342f98607c506e7f654" error_class=Encoding::UndefinedConversionError error="\"\\xE5\" from ASCII-8BIT to UTF-8"
  2017-11-12 12:56:15 +0000 [warn]: #0 suppressed same stacktrace
2017-11-12 12:56:50 +0000 [warn]: #0 failed to flush the buffer. retry_time=6 next_retry_seconds=2017-11-12 12:56:50 +0000 chunk="55dc8aba9dbc2342f98607c506e7f654" error_class=Encoding::UndefinedConversionError error="\"\\xE5\" from ASCII-8BIT to UTF-8"

**Comment by loveyang2012** [comment]
` step1: generate latest fluentd graylog gelf : gelf-latest.gem

`
where can i get this file "gelf-latest.gem" ，or can you send me by email 905883566@qq.com?
thank you very much！

**Comment by carlvine500** [comment]
[gelf-3.0.1.gem.gz](https://github.com/AliyunContainerService/log-pilot/files/5388850/gelf-3.0.1.gem.gz)
@loveyang2012  can you download it from this comment?
