### ISSUE TITLE
fluentd-pilot启动后一直报错，请帮忙看看

### ISSUE THREAD

**Issue by JasonCL2015** [AliyunContainerService/log-pilot#80]
`
<source>
@type tail
tag docker.c4b734e6a820794347dc65d9de72a4263affe3455829a6051fadec60337be52f.catalina
path /host/.
format json
time_format %Y-%m-%dT%H:%M:%S.%NZ
pos_file /pilot/pos/fluentd.pos
refresh_interval 1
</source>
<filter docker.c4b734e6a820794347dc65d9de72a4263affe3455829a6051fadec60337be52f.catalina>
@type add_time
time_key @timestamp
</filter>
<filter docker.c4b734e6a820794347dc65d9de72a4263affe3455829a6051fadec60337be52f.catalina>
@type record_transformer
<record>
  host 06b7c04598f5
  @target catalina
  docker_container r-OMS-WEB-pur-1-9c7266b0
</record>
</filter>
<match docker.**>
@type elasticsearch
hosts 10.42.91.60:9200
reconnect_on_error true
target_index_key @target
index_name _default_index
flush_interval 3
type_name fluentd
</match>
</ROOT>
[info]: following tail of /host/.
[error]: Is a directory @ io_getpartial - /host/.
[error]: /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.12.34/lib/fluent/plugin/in_tail.rb:596:in `readpartial'
[error]: /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.12.34/lib/fluent/plugin/in_tail.rb:596:in `on_notify'
[error]: /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.12.34/lib/fluent/plugin/in_tail.rb:445:in `on_notify'
[error]: /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.12.34/lib/fluent/plugin/in_tail.rb:425:in `attach'
[error]: /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.12.34/lib/fluent/plugin/in_tail.rb:198:in `setup_watcher'
[error]: /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.12.34/lib/fluent/plugin/in_tail.rb:216:in `block in start_watchers'
[error]: /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.12.34/lib/fluent/plugin/in_tail.rb:203:in `each'
[error]: /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.12.34/lib/fluent/plugin/in_tail.rb:203:in `start_watchers'
[error]: /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.12.34/lib/fluent/plugin/in_tail.rb:192:in `refresh_watchers'
[error]: /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.12.34/lib/fluent/plugin/in_tail.rb:135:in `start'
[error]: /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.12.34/lib/fluent/root_agent.rb:115:in `block in start'
[error]: /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.12.34/lib/fluent/root_agent.rb:114:in `each'
[error]: /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.12.34/lib/fluent/root_agent.rb:114:in `start'
[error]: /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.12.34/lib/fluent/engine.rb:237:in `start'
[error]: /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.12.34/lib/fluent/engine.rb:187:in `run'
[error]: /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.12.34/lib/fluent/supervisor.rb:570:in `run_engine'
[error]: /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.12.34/lib/fluent/supervisor.rb:162:in `block in start'
[error]: /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.12.34/lib/fluent/supervisor.rb:366:in `main_process'
[error]: /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.12.34/lib/fluent/supervisor.rb:339:in `block in supervise'
[error]: /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.12.34/lib/fluent/supervisor.rb:338:in `fork'
[error]: /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.12.34/lib/fluent/supervisor.rb:338:in `supervise'
[error]: /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.12.34/lib/fluent/supervisor.rb:156:in `start'
[error]: /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.12.34/lib/fluent/command/fluentd.rb:173:in `<top (required)>'
[error]: /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
[error]: /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
[error]: /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.12.34/bin/fluentd:5:in `<top (required)>'
[error]: /usr/bin/fluentd:22:in `load'
[error]: /usr/bin/fluentd:22:in `<main>'
[info]: following tail of /host/.
[error]: Is a directory @ io_getpartial - /host/.
[error]: suppressed same stacktrace
[error]: closed stream
[error]: /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.12.34/lib/fluent/plugin/in_tail.rb:596:in `readpartial'
[error]: /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.12.34/lib/fluent/plugin/in_tail.rb:596:in `on_notify'
[error]: /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.12.34/lib/fluent/plugin/in_tail.rb:445:in `on_notify'
[error]: /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.12.34/lib/fluent/plugin/in_tail.rb:530:in `on_timer'
[error]: /usr/lib/ruby/gems/2.3.0/gems/cool.io-1.4.6/lib/cool.io/loop.rb:88:in `run_once'
[error]: /usr/lib/ruby/gems/2.3.0/gems/cool.io-1.4.6/lib/cool.io/loop.rb:88:in `run'
[error]: /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.12.34/lib/fluent/plugin/in_tail.rb:285:in `run'
[error]: closed stream
[error]: /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.12.34/lib/fluent/plugin/in_tail.rb:596:in `readpartial'
[error]: /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.12.34/lib/fluent/plugin/in_tail.rb:596:in `on_notify'
[error]: /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.12.34/lib/fluent/plugin/in_tail.rb:445:in `on_notify'
 [error]: /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.12.34/lib/fluent/plugin/in_tail.rb:530:in `on_timer'
[error]: /usr/lib/ruby/gems/2.3.0/gems/cool.io-1.4.6/lib/cool.io/loop.rb:88:in `run_once'
[error]: /usr/lib/ruby/gems/2.3.0/gems/cool.io-1.4.6/lib/cool.io/loop.rb:88:in `run'
[error]: /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.12.34/lib/fluent/plugin/in_tail.rb:285:in `run'

2018/1/18 上午11:23:512018-01-18 03:23:51 +0000 [error]: closed stream
2018/1/18 上午11:23:51  2018-01-18 03:23:51 +0000 [error]: suppressed same stacktrace
2018/1/18 上午11:23:512018-01-18 03:23:51 +0000 [error]: closed stream
2018/1/18 上午11:23:51  2018-01-18 03:23:51 +0000 [error]: suppressed same stacktrace
2018/1/18 上午11:23:522018-01-18 03:23:52 +0000 [error]: closed stream
2018/1/18 上午11:23:52  2018-01-18 03:23:52 +0000 [error]: suppressed same stacktrace
2018/1/18 上午11:23:522018-01-18 03:23:52 +0000 [error]: closed stream

`

**Comment by JasonCL2015** [comment]
<source>
2018/1/18 上午11:23:49    @type tail
2018/1/18 上午11:23:49    tag docker.c4b734e6a820794347dc65d9de72a4263affe3455829a6051fadec60337be52f.catalina
2018/1/18 上午11:23:49    path /host/.
2018/1/18 上午11:23:49    format json
2018/1/18 上午11:23:49    time_format %Y-%m-%dT%H:%M:%S.%NZ
2018/1/18 上午11:23:49    pos_file /pilot/pos/fluentd.pos
2018/1/18 上午11:23:49    refresh_interval 1
2018/1/18 上午11:23:49  </source>
2018/1/18 上午11:23:49  <filter docker.c4b734e6a820794347dc65d9de72a4263affe3455829a6051fadec60337be52f.catalina>
2018/1/18 上午11:23:49    @type add_time
2018/1/18 上午11:23:49    time_key @timestamp
2018/1/18 上午11:23:49  </filter>
2018/1/18 上午11:23:49  <filter docker.c4b734e6a820794347dc65d9de72a4263affe3455829a6051fadec60337be52f.catalina>
2018/1/18 上午11:23:49    @type record_transformer
2018/1/18 上午11:23:49    <record>
2018/1/18 上午11:23:49      host 06b7c04598f5
2018/1/18 上午11:23:49      @target catalina
2018/1/18 上午11:23:49      docker_container r-OMS-WEB-pur-1-9c7266b0
2018/1/18 上午11:23:49    </record>
2018/1/18 上午11:23:49  </filter>
2018/1/18 上午11:23:49  <match docker.**>
2018/1/18 上午11:23:49    @type elasticsearch
2018/1/18 上午11:23:49    hosts 10.42.91.60:9200
2018/1/18 上午11:23:49    reconnect_on_error true
2018/1/18 上午11:23:49    target_index_key @target
2018/1/18 上午11:23:49    index_name _default_index
2018/1/18 上午11:23:49    flush_interval 3
2018/1/18 上午11:23:49    type_name fluentd
2018/1/18 上午11:23:49  </match>
2018/1/18 上午11:23:49</ROOT>
2018/1/18 上午11:23:492018-01-18 03:23:49 +0000 [info]: following tail of /host/.
2018/1/18 上午11:23:492018-01-18 03:23:49 +0000 [error]: Is a directory @ io_getpartial - /host/.
2018/1/18 上午11:23:49  2018-01-18 03:23:49 +0000 [error]: /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.12.34/lib/fluent/plugin/in_tail.rb:596:in `readpartial'
2018/1/18 上午11:23:49  2018-01-18 03:23:49 +0000 [error]: /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.12.34/lib/fluent/plugin/in_tail.rb:596:in `on_notify'
2018/1/18 上午11:23:49  2018-01-18 03:23:49 +0000 [error]: /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.12.34/lib/fluent/plugin/in_tail.rb:445:in `on_notify'
2018/1/18 上午11:23:49  2018-01-18 03:23:49 +0000 [error]: /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.12.34/lib/fluent/plugin/in_tail.rb:425:in `attach'
2018/1/18 上午11:23:49  2018-01-18 03:23:49 +0000 [error]: /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.12.34/lib/fluent/plugin/in_tail.rb:198:in `setup_watcher'
2018/1/18 上午11:23:49  2018-01-18 03:23:49 +0000 [error]: /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.12.34/lib/fluent/plugin/in_tail.rb:216:in `block in start_watchers'
2018/1/18 上午11:23:49  2018-01-18 03:23:49 +0000 [error]: /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.12.34/lib/fluent/plugin/in_tail.rb:203:in `each'
2018/1/18 上午11:23:49  2018-01-18 03:23:49 +0000 [error]: /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.12.34/lib/fluent/plugin/in_tail.rb:203:in `start_watchers'
2018/1/18 上午11:23:49  2018-01-18 03:23:49 +0000 [error]: /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.12.34/lib/fluent/plugin/in_tail.rb:192:in `refresh_watchers'
2018/1/18 上午11:23:49  2018-01-18 03:23:49 +0000 [error]: /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.12.34/lib/fluent/plugin/in_tail.rb:135:in `start'
2018/1/18 上午11:23:49  2018-01-18 03:23:49 +0000 [error]: /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.12.34/lib/fluent/root_agent.rb:115:in `block in start'
2018/1/18 上午11:23:49  2018-01-18 03:23:49 +0000 [error]: /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.12.34/lib/fluent/root_agent.rb:114:in `each'
2018/1/18 上午11:23:49  2018-01-18 03:23:49 +0000 [error]: /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.12.34/lib/fluent/root_agent.rb:114:in `start'
2018/1/18 上午11:23:49  2018-01-18 03:23:49 +0000 [error]: /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.12.34/lib/fluent/engine.rb:237:in `start'
2018/1/18 上午11:23:49  2018-01-18 03:23:49 +0000 [error]: /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.12.34/lib/fluent/engine.rb:187:in `run'
2018/1/18 上午11:23:49  2018-01-18 03:23:49 +0000 [error]: /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.12.34/lib/fluent/supervisor.rb:570:in `run_engine'
2018/1/18 上午11:23:49  2018-01-18 03:23:49 +0000 [error]: /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.12.34/lib/fluent/supervisor.rb:162:in `block in start'
2018/1/18 上午11:23:49  2018-01-18 03:23:49 +0000 [error]: /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.12.34/lib/fluent/supervisor.rb:366:in `main_process'
2018/1/18 上午11:23:49  2018-01-18 03:23:49 +0000 [error]: /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.12.34/lib/fluent/supervisor.rb:339:in `block in supervise'
2018/1/18 上午11:23:49  2018-01-18 03:23:49 +0000 [error]: /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.12.34/lib/fluent/supervisor.rb:338:in `fork'
2018/1/18 上午11:23:49  2018-01-18 03:23:49 +0000 [error]: /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.12.34/lib/fluent/supervisor.rb:338:in `supervise'
2018/1/18 上午11:23:49  2018-01-18 03:23:49 +0000 [error]: /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.12.34/lib/fluent/supervisor.rb:156:in `start'
2018/1/18 上午11:23:49  2018-01-18 03:23:49 +0000 [error]: /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.12.34/lib/fluent/command/fluentd.rb:173:in `<top (required)>'
2018/1/18 上午11:23:49  2018-01-18 03:23:49 +0000 [error]: /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
2018/1/18 上午11:23:49  2018-01-18 03:23:49 +0000 [error]: /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
2018/1/18 上午11:23:49  2018-01-18 03:23:49 +0000 [error]: /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.12.34/bin/fluentd:5:in `<top (required)>'
2018/1/18 上午11:23:49  2018-01-18 03:23:49 +0000 [error]: /usr/bin/fluentd:22:in `load'
2018/1/18 上午11:23:49  2018-01-18 03:23:49 +0000 [error]: /usr/bin/fluentd:22:in `<main>'
2018/1/18 上午11:23:492018-01-18 03:23:49 +0000 [info]: following tail of /host/.
2018/1/18 上午11:23:492018-01-18 03:23:49 +0000 [error]: Is a directory @ io_getpartial - /host/.
2018/1/18 上午11:23:49  2018-01-18 03:23:49 +0000 [error]: suppressed same stacktrace
2018/1/18 上午11:23:502018-01-18 03:23:50 +0000 [error]: closed stream
2018/1/18 上午11:23:50  2018-01-18 03:23:50 +0000 [error]: /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.12.34/lib/fluent/plugin/in_tail.rb:596:in `readpartial'
2018/1/18 上午11:23:50  2018-01-18 03:23:50 +0000 [error]: /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.12.34/lib/fluent/plugin/in_tail.rb:596:in `on_notify'
2018/1/18 上午11:23:50  2018-01-18 03:23:50 +0000 [error]: /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.12.34/lib/fluent/plugin/in_tail.rb:445:in `on_notify'
2018/1/18 上午11:23:50  2018-01-18 03:23:50 +0000 [error]: /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.12.34/lib/fluent/plugin/in_tail.rb:530:in `on_timer'
2018/1/18 上午11:23:50  2018-01-18 03:23:50 +0000 [error]: /usr/lib/ruby/gems/2.3.0/gems/cool.io-1.4.6/lib/cool.io/loop.rb:88:in `run_once'
2018/1/18 上午11:23:50  2018-01-18 03:23:50 +0000 [error]: /usr/lib/ruby/gems/2.3.0/gems/cool.io-1.4.6/lib/cool.io/loop.rb:88:in `run'
2018/1/18 上午11:23:50  2018-01-18 03:23:50 +0000 [error]: /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.12.34/lib/fluent/plugin/in_tail.rb:285:in `run'
2018/1/18 上午11:23:502018-01-18 03:23:50 +0000 [error]: closed stream
2018/1/18 上午11:23:50  2018-01-18 03:23:50 +0000 [error]: /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.12.34/lib/fluent/plugin/in_tail.rb:596:in `readpartial'
2018/1/18 上午11:23:50  2018-01-18 03:23:50 +0000 [error]: /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.12.34/lib/fluent/plugin/in_tail.rb:596:in `on_notify'
2018/1/18 上午11:23:50  2018-01-18 03:23:50 +0000 [error]: /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.12.34/lib/fluent/plugin/in_tail.rb:445:in `on_notify'
2018/1/18 上午11:23:50  2018-01-18 03:23:50 +0000 [error]: /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.12.34/lib/fluent/plugin/in_tail.rb:530:in `on_timer'
2018/1/18 上午11:23:50  2018-01-18 03:23:50 +0000 [error]: /usr/lib/ruby/gems/2.3.0/gems/cool.io-1.4.6/lib/cool.io/loop.rb:88:in `run_once'
2018/1/18 上午11:23:50  2018-01-18 03:23:50 +0000 [error]: /usr/lib/ruby/gems/2.3.0/gems/cool.io-1.4.6/lib/cool.io/loop.rb:88:in `run'
2018/1/18 上午11:23:50  2018-01-18 03:23:50 +0000 [error]: /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.12.34/lib/fluent/plugin/in_tail.rb:285:in `run'
2018/1/18 上午11:23:512018-01-18 03:23:51 +0000 [error]: closed stream
2018/1/18 上午11:23:51  2018-01-18 03:23:51 +0000 [error]: suppressed same stacktrace
2018/1/18 上午11:23:512018-01-18 03:23:51 +0000 [error]: closed stream
2018/1/18 上午11:23:51  2018-01-18 03:23:51 +0000 [error]: suppressed same stacktrace
2018/1/18 上午11:23:522018-01-18 03:23:52 +0000 [error]: closed stream
2018/1/18 上午11:23:52  2018-01-18 03:23:52 +0000 [error]: suppressed same stacktrace
2018/1/18 上午11:23:522018-01-18 03:23:52 +0000 [error]: closed stream
2018/1/18 上午11:23:52  2018-01-18 03:23:52 +0000 [error]: suppressed same stacktrace
2018/1/18 上午11:23:532018-01-18 03:23:53 +0000 [error]: closed stream
2018/1/18 上午11:23:53  2018-01-18 03:23:53 +0000 [error]: suppressed same stacktrace
2018/1/18 上午11:23:532018-01-18 03:23:53 +0000 [error]: closed stream
2018/1/18 上午11:23:53  2018-01-18 03:23:53 +0000 [error]: suppressed same stacktrace
2018/1/18 上午11:23:542018-01-18 03:23:54 +0000 [error]: closed stream
2018/1/18 上午11:23:54  2018-01-18 03:23:54 +0000 [error]: suppressed same stacktrace
2018/1/18 上午11:23:542018-01-18 03:23:54 +0000 [error]: closed stream
2018/1/18 上午11:23:54  2018-01-18 03:23:54 +0000 [error]: suppressed same stacktrace
2018/1/18 上午11:23:552018-01-18 03:23:55 +0000 [error]: closed stream
2018/1/18 上午11:23:55  2018-01-18 03:23:55 +0000 [error]: suppressed same stacktrace
2018/1/18 上午11:23:552018-01-18 03:23:55 +0000 [error]: closed stream
2018/1/18 上午11:23:55  2018-01-18 03:23:55 +0000 [error]: suppressed same stacktrace
2018/1/18 上午11:23:562018-01-18 03:23:56 +0000 [error]: closed stream
2018/1/18 上午11:23:56  2018-01-18 03:23:56 +0000 [error]: suppressed same stacktrace
2018/1/18 上午11:23:562018-01-18 03:23:56 +0000 [error]: closed stream
2018/1/18 上午11:23:56  2018-01-18 03:23:56 +0000 [error]: suppressed same stacktrace
2018/1/18 上午11:23:572018-01-18 03:23:57 +0000 [error]: closed stream
2018/1/18 上午11:23:572018-01-18 03:23:57 +0000 [error]: closed stream
2018/1/18 上午11:23:57  2018-01-18 03:23:57 +0000 [error]: suppressed same stacktrace
2018/1/18 上午11:23:57  2018-01-18 03:23:57 +0000 [error]: suppressed same stacktrace
2018/1/18 上午11:23:582018-01-18 03:23:58 +0000 [error]: closed stream
2018/1/18 上午11:23:58  2018-01-18 03:23:58 +0000 [error]: suppressed same stacktrace
2018/1/18 上午11:23:582018-01-18 03:23:58 +0000 [error]: closed stream
2018/1/18 上午11:23:58  2018-01-18 03:23:58 +0000 [error]: suppressed same stacktrace
2018/1/18 上午11:23:592018-01-18 03:23:59 +0000 [error]: closed stream
2018/1/18 上午11:23:59  2018-01-18 03:23:59 +0000 [error]: suppressed same stacktrace
2018/1/18 上午11:23:592018-01-18 03:23:59 +0000 [error]: closed stream
2018/1/18 上午11:23:59  2018-01-18 03:23:59 +0000 [error]: suppressed same stacktrace
2018/1/18 上午11:24:002018-01-18 03:24:00 +0000 [error]: closed stream
2018/1/18 上午11:24:00  2018-01-18 03:24:00 +0000 [error]: suppressed same stacktrace
2018/1/18 上午11:24:002018-01-18 03:24:00 +0000 [error]: closed stream
2018/1/18 上午11:24:00  2018-01-18 03:24:00 +0000 [error]: suppressed same stacktrace
2018/1/18 上午11:24:012018-01-18 03:24:01 +0000 [error]: closed stream
2018/1/18 上午11:24:01  2018-01-18 03:24:01 +0000 [error]: suppressed same stacktrace
2018/1/18 上午11:24:012018-01-18 03:24:01 +0000 [error]: closed stream
2018/1/18 上午11:24:01  2018-01-18 03:24:01 +0000 [error]: suppressed same stacktrace
2018/1/18 上午11:24:022018-01-18 03:24:02 +0000 [error]: closed stream
2018/1/18 上午11:24:02  2018-01-18 03:24:02 +0000 [error]: suppressed same stacktrace
2018/1/18 上午11:24:022018-01-18 03:24:02 +0000 [error]: closed stream
2018/1/18 上午11:24:02  2018-01-18 03:24:02 +0000 [error]: suppressed same stacktrace
2018/1/18 上午11:24:032018-01-18 03:24:03 +0000 [error]: closed stream
2018/1/18 上午11:24:03  2018-01-18 03:24:03 +0000 [error]: suppressed same stacktrace
2018/1/18 上午11:24:032018-01-18 03:24:03 +0000 [error]: closed stream
2018/1/18 上午11:24:03  2018-01-18 03:24:03 +0000 [error]: suppressed same stacktrace
2018/1/18 上午11:24:042018-01-18 03:24:04 +0000 [error]: closed stream
2018/1/18 上午11:24:04  2018-01-18 03:24:04 +0000 [error]: suppressed same stacktrace
2018/1/18 上午11:24:042018-01-18 03:24:04 +0000 [error]: closed stream
2018/1/18 上午11:24:04  2018-01-18 03:24:04 +0000 [error]: suppressed same stacktrace
2018/1/18 上午11:24:052018-01-18 03:24:05 +0000 [error]: closed stream
2018/1/18 上午11:24:05  2018-01-18 03:24:05 +0000 [error]: suppressed same stacktrace
2018/1/18 上午11:24:052018-01-18 03:24:05 +0000 [error]: closed stream
2018/1/18 上午11:24:05  2018-01-18 03:24:05 +0000 [error]: suppressed same stacktrace
2018/1/18 上午11:24:062018-01-18 03:24:06 +0000 [error]: closed stream
2018/1/18 上午11:24:062018-01-18 03:24:06 +0000 [error]: closed stream
2018/1/18 上午11:24:06  2018-01-18 03:24:06 +0000 [error]: suppressed same stacktrace
2018/1/18 上午11:24:06  2018-01-18 03:24:06 +0000 [error]: suppressed same stacktrace
2018/1/18 上午11:24:072018-01-18 03:24:07 +0000 [error]: closed stream
2018/1/18 上午11:24:07  2018-01-18 03:24:07 +0000 [error]: suppressed same stacktrace
2018/1/18 上午11:24:072018-01-18 03:24:07 +0000 [error]: closed stream
2018/1/18 上午11:24:07  2018-01-18 03:24:07 +0000 [error]: suppressed same stacktrace
2018/1/18 上午11:24:082018-01-18 03:24:08 +0000 [error]: closed stream
2018/1/18 上午11:24:08  2018-01-18 03:24:08 +0000 [error]: suppressed same stacktrace
