### ISSUE TITLE
Follow the quickstart and log-pilot print " [error]: #0 Is a directory @ io_getpartial - /host/. [error]: #0 suppressed same stacktrace" 

### ISSUE THREAD

**Issue by crystonesc** [AliyunContainerService/log-pilot#97]
2018-03-30 11:08:22 +0000 [error]: #0 Is a directory @ io_getpartial - /host/.
  2018-03-30 11:08:22 +0000 [error]: #0 /usr/lib/ruby/gems/2.3.0/gems/fluentd-1.0.2/lib/fluent/plugin/in_tail.rb:692:in `readpartial'
  2018-03-30 11:08:22 +0000 [error]: #0 /usr/lib/ruby/gems/2.3.0/gems/fluentd-1.0.2/lib/fluent/plugin/in_tail.rb:692:in `block in on_notify'
  2018-03-30 11:08:22 +0000 [error]: #0 /usr/lib/ruby/gems/2.3.0/gems/fluentd-1.0.2/lib/fluent/plugin/in_tail.rb:751:in `with_io'
  2018-03-30 11:08:22 +0000 [error]: #0 /usr/lib/ruby/gems/2.3.0/gems/fluentd-1.0.2/lib/fluent/plugin/in_tail.rb:685:in `on_notify'
  2018-03-30 11:08:22 +0000 [error]: #0 /usr/lib/ruby/gems/2.3.0/gems/fluentd-1.0.2/lib/fluent/plugin/in_tail.rb:534:in `on_notify'
  2018-03-30 11:08:22 +0000 [error]: #0 /usr/lib/ruby/gems/2.3.0/gems/fluentd-1.0.2/lib/fluent/plugin/in_tail.rb:507:in `attach'
  2018-03-30 11:08:22 +0000 [error]: #0 /usr/lib/ruby/gems/2.3.0/gems/fluentd-1.0.2/lib/fluent/plugin/in_tail.rb:264:in `setup_watcher'
  2018-03-30 11:08:22 +0000 [error]: #0 /usr/lib/ruby/gems/2.3.0/gems/fluentd-1.0.2/lib/fluent/plugin/in_tail.rb:292:in `block in start_watchers'
  2018-03-30 11:08:22 +0000 [error]: #0 /usr/lib/ruby/gems/2.3.0/gems/fluentd-1.0.2/lib/fluent/plugin/in_tail.rb:278:in `each'
  2018-03-30 11:08:22 +0000 [error]: #0 /usr/lib/ruby/gems/2.3.0/gems/fluentd-1.0.2/lib/fluent/plugin/in_tail.rb:278:in `start_watchers'
  2018-03-30 11:08:22 +0000 [error]: #0 /usr/lib/ruby/gems/2.3.0/gems/fluentd-1.0.2/lib/fluent/plugin/in_tail.rb:258:in `refresh_watchers'
  2018-03-30 11:08:22 +0000 [error]: #0 /usr/lib/ruby/gems/2.3.0/gems/fluentd-1.0.2/lib/fluent/plugin/in_tail.rb:193:in `start'
  2018-03-30 11:08:22 +0000 [error]: #0 /usr/lib/ruby/gems/2.3.0/gems/fluentd-1.0.2/lib/fluent/root_agent.rb:165:in `block in start'
  2018-03-30 11:08:22 +0000 [error]: #0 /usr/lib/ruby/gems/2.3.0/gems/fluentd-1.0.2/lib/fluent/root_agent.rb:154:in `block (2 levels) in lifecycle'
  2018-03-30 11:08:22 +0000 [error]: #0 /usr/lib/ruby/gems/2.3.0/gems/fluentd-1.0.2/lib/fluent/root_agent.rb:153:in `each'
  2018-03-30 11:08:22 +0000 [error]: #0 /usr/lib/ruby/gems/2.3.0/gems/fluentd-1.0.2/lib/fluent/root_agent.rb:153:in `block in lifecycle'
  2018-03-30 11:08:22 +0000 [error]: #0 /usr/lib/ruby/gems/2.3.0/gems/fluentd-1.0.2/lib/fluent/root_agent.rb:140:in `each'
  2018-03-30 11:08:22 +0000 [error]: #0 /usr/lib/ruby/gems/2.3.0/gems/fluentd-1.0.2/lib/fluent/root_agent.rb:140:in `lifecycle'
  2018-03-30 11:08:22 +0000 [error]: #0 /usr/lib/ruby/gems/2.3.0/gems/fluentd-1.0.2/lib/fluent/root_agent.rb:164:in `start'
  2018-03-30 11:08:22 +0000 [error]: #0 /usr/lib/ruby/gems/2.3.0/gems/fluentd-1.0.2/lib/fluent/engine.rb:274:in `start'
  2018-03-30 11:08:22 +0000 [error]: #0 /usr/lib/ruby/gems/2.3.0/gems/fluentd-1.0.2/lib/fluent/engine.rb:219:in `run'
  2018-03-30 11:08:22 +0000 [error]: #0 /usr/lib/ruby/gems/2.3.0/gems/fluentd-1.0.2/lib/fluent/supervisor.rb:774:in `run_engine'
  2018-03-30 11:08:22 +0000 [error]: #0 /usr/lib/ruby/gems/2.3.0/gems/fluentd-1.0.2/lib/fluent/supervisor.rb:523:in `block in run_worker'
  2018-03-30 11:08:22 +0000 [error]: #0 /usr/lib/ruby/gems/2.3.0/gems/fluentd-1.0.2/lib/fluent/supervisor.rb:699:in `main_process'
  2018-03-30 11:08:22 +0000 [error]: #0 /usr/lib/ruby/gems/2.3.0/gems/fluentd-1.0.2/lib/fluent/supervisor.rb:518:in `run_worker'
  2018-03-30 11:08:22 +0000 [error]: #0 /usr/lib/ruby/gems/2.3.0/gems/fluentd-1.0.2/lib/fluent/command/fluentd.rb:316:in `<top (required)>'
  2018-03-30 11:08:22 +0000 [error]: #0 /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
  2018-03-30 11:08:22 +0000 [error]: #0 /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
  2018-03-30 11:08:22 +0000 [error]: #0 /usr/lib/ruby/gems/2.3.0/gems/fluentd-1.0.2/bin/fluentd:8:in `<top (required)>'
  2018-03-30 11:08:22 +0000 [error]: #0 /usr/bin/fluentd:22:in `load'
  2018-03-30 11:08:22 +0000 [error]: #0 /usr/bin/fluentd:22:in `<main>'
2018-03-30 11:08:22 +0000 [info]: #0 following tail of /host/var/lib/docker/volumes/a1b479b64e768632b4315d1309ddf77d21268099de05c53c87db1b98edc5527b/_data/localhost_access_log.2018-03-30.txt
2018-03-30 11:08:22 +0000 [info]: #0 disable filter chain optimization because [Fluent::Plugin::RecordTransformerFilter] uses `#filter_stream` method.
2018-03-30 11:08:22.686301733 +0000 docker.1e3c26d28945c9023c894290f2e6802ea0f879e06b032c2e35ef523d541f206f.access: {"message":"192.168.60.1 - - [30/Mar/2018:11:08:03 +0000] \"GET / HTTP/1.1\" 200 11250","@timestamp":"2018-03-30T11:08:22.686","host":"9e1c7ba3ab41","index":"access","topic":"access","@target":"access","docker_container":"loving_golick"}
2018-03-30 11:08:22 +0000 [info]: #0 fluentd worker is now running worker=0
2018-03-30 11:08:23 +0000 [error]: #0 Is a directory @ io_getpartial - /host/.
  2018-03-30 11:08:23 +0000 [error]: #0 /usr/lib/ruby/gems/2.3.0/gems/fluentd-1.0.2/lib/fluent/plugin/in_tail.rb:692:in `readpartial'
  2018-03-30 11:08:23 +0000 [error]: #0 /usr/lib/ruby/gems/2.3.0/gems/fluentd-1.0.2/lib/fluent/plugin/in_tail.rb:692:in `block in on_notify'
  2018-03-30 11:08:23 +0000 [error]: #0 /usr/lib/ruby/gems/2.3.0/gems/fluentd-1.0.2/lib/fluent/plugin/in_tail.rb:751:in `with_io'
  2018-03-30 11:08:23 +0000 [error]: #0 /usr/lib/ruby/gems/2.3.0/gems/fluentd-1.0.2/lib/fluent/plugin/in_tail.rb:685:in `on_notify'
  2018-03-30 11:08:23 +0000 [error]: #0 /usr/lib/ruby/gems/2.3.0/gems/fluentd-1.0.2/lib/fluent/plugin/in_tail.rb:534:in `on_notify'
  2018-03-30 11:08:23 +0000 [error]: #0 /usr/lib/ruby/gems/2.3.0/gems/fluentd-1.0.2/lib/fluent/plugin_helper/timer.rb:77:in `on_timer'
  2018-03-30 11:08:23 +0000 [error]: #0 /usr/lib/ruby/gems/2.3.0/gems/cool.io-1.5.3/lib/cool.io/loop.rb:88:in `run_once'
  2018-03-30 11:08:23 +0000 [error]: #0 /usr/lib/ruby/gems/2.3.0/gems/cool.io-1.5.3/lib/cool.io/loop.rb:88:in `run'
  2018-03-30 11:08:23 +0000 [error]: #0 /usr/lib/ruby/gems/2.3.0/gems/fluentd-1.0.2/lib/fluent/plugin_helper/event_loop.rb:84:in `block in start'
  2018-03-30 11:08:23 +0000 [error]: #0 /usr/lib/ruby/gems/2.3.0/gems/fluentd-1.0.2/lib/fluent/plugin_helper/thread.rb:78:in `block in thread_create'
2018-03-30 11:08:24 +0000 [error]: #0 Is a directory @ io_getpartial - /host/.
  2018-03-30 11:08:24 +0000 [error]: #0 suppressed same stacktrace
2018-03-30 11:08:25 +0000 [error]: #0 Is a directory @ io_getpartial - /host/.
  2018-03-30 11:08:25 +0000 [error]: #0 suppressed same stacktrace
2018-03-30 11:08:26 +0000 [error]: #0 Is a directory @ io_getpartial - /host/.
  2018-03-30 11:08:26 +0000 [error]: #0 suppressed same stacktrace

**Comment by crystonesc** [comment]
我现在发现，通过pilot-type=filebeat启动以后，没有出现报错
